# -*- coding: UTF-8 -*-
# LIMA NVDA add-on: Firebase / Google OAuth configuration.
#
# The four project values (client id/secret, API key, project id) are NOT kept
# here. They live in secret_config.py, which is gitignored so the secrets stay
# out of git. Create that file locally (see the four names below) from your
# Google Cloud / Firebase consoles. For a desktop OAuth client none of these are
# truly confidential, but keeping them out of the repo is good hygiene.
#
# Also required in the consoles (no code change needed):
#   * Firebase -> Authentication -> Sign-in method -> enable Google.
#   * Firestore rule so each user can only write their own doc:
#       match /users/{uid} { allow read, write: if request.auth.uid == uid; }

try:
	from . import secret_config
	GOOGLE_CLIENT_ID = secret_config.GOOGLE_CLIENT_ID
	GOOGLE_CLIENT_SECRET = secret_config.GOOGLE_CLIENT_SECRET
	FIREBASE_API_KEY = secret_config.FIREBASE_API_KEY
	FIREBASE_PROJECT_ID = secret_config.FIREBASE_PROJECT_ID
except ImportError:
	# No secret_config.py present; sign-in stays disabled (is_configured()
	# returns False) rather than breaking the add-on load.
	GOOGLE_CLIENT_ID = GOOGLE_CLIENT_SECRET = FIREBASE_API_KEY = FIREBASE_PROJECT_ID = ""

# Firestore database id (not secret). Use "(default)" unless the project uses a
# named database (Firebase console -> Firestore -> the database's id). This
# product has its own dedicated database, so user docs are flat.
FIREBASE_DATABASE_ID = "lima-nvda-addon-firestore-db"

# ---------------------------------------------------------------------------
# Environment (dev vs prod) — selected at BUILD time, never by editing this file
# ---------------------------------------------------------------------------
# Both environments' values are committed here. Which one a build uses comes from
# build_env.py, which sconstruct generates and .gitignore excludes:
#
#   scons          -> build_env.LIMA_ENV = "prod"
#   scons dev=1    -> build_env.LIMA_ENV = "dev"
#
# DO NOT hand-edit these to switch environments and then revert. That is what the
# build flag is for; editing them makes branches diverge and risks shipping a build
# pointed at the wrong backend (or, worse, writing test data into the prod `users`
# collection).
#
# The two values in each entry MUST move together. FIRESTORE_USERS_COLLECTION has to
# match the auth server's USERS_COLLECTION for that backend, because the add-on writes
# the sign-in profile to Firestore directly while the server writes the OpenRouter
# fields to the SAME document. Mismatch them and user records split in half.
#
# Confirm a backend URL with:
#   gcloud run services describe SERVICE --region us-west1 --format="value(status.url)"
_ENVIRONMENTS = {
	"prod": {
		"backend_url": "https://lima-addon-auth-server-423416231887.us-west1.run.app",
		"users_collection": "users",
	},
	"dev": {
		"backend_url": "https://lima-addon-auth-server-dev-423416231887.us-west1.run.app",
		"users_collection": "users_dev",
	},
}

try:
	from .build_env import LIMA_ENV
except ImportError:
	# Unbuilt source checkout (build_env.py is generated by sconstruct). Fall back to
	# dev deliberately: an unmarked tree is a developer's, and pointing it at dev fails
	# loudly and harmlessly, whereas defaulting to prod would silently write test data
	# into live user documents.
	LIMA_ENV = "dev"

if LIMA_ENV not in _ENVIRONMENTS:
	raise RuntimeError(
		"Unknown LIMA_ENV %r in build_env.py; expected one of %s"
		% (LIMA_ENV, sorted(_ENVIRONMENTS))
	)

#: Base URL of the LIMA Cloud Run backend (not secret). All AI calls are proxied through
#: it so the OpenRouter key never reaches the client; the add-on authenticates each call
#: with the user's Firebase ID token.
LIMA_BACKEND_URL = _ENVIRONMENTS[LIMA_ENV]["backend_url"]

#: Firestore collection holding per-user docs, matched to the backend above.
FIRESTORE_USERS_COLLECTION = _ENVIRONMENTS[LIMA_ENV]["users_collection"]


def is_configured():
	"""True when the values needed to run sign-in have been injected."""
	return bool(GOOGLE_CLIENT_ID and FIREBASE_API_KEY and FIREBASE_PROJECT_ID)


def get_config():
	"""Return a FirebaseConfig built from the injected values."""
	from . import auth
	return auth.FirebaseConfig(
		GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, FIREBASE_API_KEY, FIREBASE_PROJECT_ID,
		FIREBASE_DATABASE_ID or "(default)",
		FIRESTORE_USERS_COLLECTION or "users",
	)
